name: find_apartment
channels:
  - conda-forge
dependencies:
  - python=3.11
  - beautifulsoup4==4.13.4
  - matplotlib==3.10.1
  - numpy==2.2.5
  - pandas==2.2.3
  - requests==2.32.3
  - seaborn==0.13.2
  - tqdm==4.67.1
  - streamlit==1.44.1